# Generated by Django 2.2.28 on 2022-08-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_suppplier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='suppplier',
            new_name='supplier',
        ),
    ]
