# Generated by Django 4.1 on 2022-08-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='p_dtls',
            fields=[
                ('pm_id', models.AutoField(default=100, primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='p_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, default='', null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='p_master',
            fields=[
                ('pm_id', models.AutoField(default=100, primary_key=True, serialize=False)),
                ('invoice', models.IntegerField()),
                ('invoicedate', models.DateField(blank=True, default='', null=True)),
                ('sname', models.CharField(max_length=50)),
                ('sadd', models.TextField(max_length=255)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='p_temp',
            fields=[
                ('pm_id', models.AutoField(default=100, primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('sid', models.AutoField(default=None, editable=b'I00\n', primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=255)),
                ('semail', models.EmailField(max_length=35)),
                ('smob', models.CharField(max_length=255)),
                ('sadd', models.CharField(max_length=255)),
                ('sdate', models.DateField(blank=True, default='', null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
