# Generated by Django 4.1 on 2022-08-21 19:08

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_dtls',
            name='sid',
            field=models.ForeignKey(default='', on_delete=builtins.callable, to='app.supplier'),
        ),
        migrations.AddField(
            model_name='p_temp',
            name='sid',
            field=models.ForeignKey(default='', on_delete=builtins.callable, to='app.supplier'),
        ),
    ]
