# Generated by Django 4.1 on 2022-08-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmastermodel',
            options={'managed': False},
        ),
    ]
