# Generated by Django 4.1 on 2022-08-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_itemmastermodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmastermodel',
            options={},
        ),
    ]
