# Generated by Django 4.1 on 2022-08-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_itemmastermodel_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemmastermodel',
            table='tbl_items_master',
        ),
    ]
