# Generated by Django 4.1 on 2022-08-30 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_delete_purchase_detailsmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierMasterModel',
        ),
    ]
