# Generated by Django 4.1 on 2022-08-28 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMasterModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(max_length=200)),
                ('status', models.SmallIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_MasterModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_no', models.CharField(max_length=200)),
                ('sales_date', models.DateField()),
                ('customer_name', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SalesDetailsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.itemmastermodel')),
                ('sales_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales_mastermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_tempModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.itemmastermodel')),
            ],
        ),
    ]
