# Generated by Django 4.1 on 2022-08-28 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sales_tempmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales_tempmodel',
            options={},
        ),
    ]
