# Generated by Django 4.1 on 2022-08-30 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('sales', '0003_alter_sales_tempmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_mastermodel',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sales_tempmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemmastermodel'),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemmastermodel'),
        ),
        migrations.DeleteModel(
            name='ItemMasterModel',
        ),
    ]
