# Generated by Django 4.1 on 2022-08-30 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sales_mastermodel_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_mastermodel',
            name='mobile',
        ),
    ]
