# Generated by Django 4.1 on 2022-09-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_sales_mastermodel_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdetailsmodel',
            name='av_qty',
            field=models.IntegerField(null=True),
        ),
    ]
