# Generated by Django 2.2.28 on 2022-08-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220823_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
