# Generated by Django 4.1 on 2022-08-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliermastermodel',
            options={'managed': False},
        ),
    ]
