# Generated by Django 4.1 on 2022-08-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_itemmastermodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmastermodel',
            options={},
        ),
    ]
