# Generated by Django 4.1 on 2022-09-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_itemmastermodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemMasterModel',
        ),
    ]
