# Generated by Django 4.1 on 2022-08-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmastermodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sales_mastermodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sales_tempmodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='salesdetailsmodel',
            options={'managed': False},
        ),
    ]
