# Generated by Django 4.1 on 2022-08-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_itemmastermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemmastermodel',
            table='tbl_items_master',
        ),
        migrations.AlterModelTable(
            name='sales_mastermodel',
            table='tbl_sales_master',
        ),
        migrations.AlterModelTable(
            name='sales_tempmodel',
            table='tbl_temp_sales',
        ),
        migrations.AlterModelTable(
            name='salesdetailsmodel',
            table='tbl_sales_details',
        ),
    ]
